name = "Baselet"
uuid = "9718e550-a3fa-408a-8086-8db961cd8217"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.1"

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Random", "Test"]
